org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.java.installations.paths=/opt/homebrew/opt/openjdk@25

java_version=25
minecraft_version=26.3
minecraft_version_range=[26.3]
neo_version=26.3.0.40-beta

mod_id=thaumcraft
mod_name=Thaumcraft Reforged
mod_license=All Rights Reserved
mod_version=3.0.5e-reforged.1
mod_group_id=thaumcraft
mod_authors=Azanor (original), oki (port)
jei_version=31.8.0.53
