org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.java.installations.paths=/opt/homebrew/opt/openjdk@21

java_version=21
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.256
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_id=thaumcraft
mod_name=Thaumcraft Reforged
mod_license=All Rights Reserved
mod_version=3.0.5e-reforged.1
mod_group_id=thaumcraft
mod_authors=Azanor (original), overseas (port)
jei_version=19.57.0.451
