package thaumcraft.aspect;

import java.util.List;

public final class ConfigAspects extends AspectRegistrar {
    public ConfigAspects(AspectRegistry registry) {
        super(registry);
    }

    public void registerAll() {
        register("minecraft:cobblestone", tags().add(Aspect.ROCK, 1).add(Aspect.DESTRUCTION, 1));
        register("minecraft:stone", tags().add(Aspect.ROCK, 2));
        register("minecraft:end_stone", tags().add(Aspect.EARTH, 1).add(Aspect.ROCK, 1).add(Aspect.DARK, 1));
        register("#minecraft:sand", tags().add(Aspect.EARTH, 2));
        register("minecraft:dirt", tags().add(Aspect.EARTH, 2));
        register("minecraft:grass_block", tags().add(Aspect.EARTH, 2).add(Aspect.PLANT, 1));
        register("minecraft:gravel", tags().add(Aspect.EARTH, 1).add(Aspect.ROCK, 1));
        register("minecraft:mycelium", tags().add(Aspect.EARTH, 2).add(Aspect.FUNGUS, 1));
        register("minecraft:clay_ball", tags().add(Aspect.EARTH, 2).add(Aspect.WATER, 1));
        register("minecraft:clay", tags().add(Aspect.EARTH, 6).add(Aspect.WATER, 3));
        register("minecraft:gold_nugget", tags().add(Aspect.METAL, 1));
        register(List.of("minecraft:iron_nugget", "thaumcraft:tin_nugget", "thaumcraft:silver_nugget", "thaumcraft:lead_nugget", "thaumcraft:quicksilver_drop", "thaumcraft:native_copper_cluster", "thaumcraft:native_tin_cluster", "thaumcraft:native_silver_cluster", "thaumcraft:native_lead_cluster"), tags().add(Aspect.METAL, 1));
        register("minecraft:brick", tags().add(Aspect.EARTH, 2).add(Aspect.FIRE, 1));
        register("minecraft:soul_sand", tags().add(Aspect.EARTH, 1).add(Aspect.TRAP, 1).add(Aspect.SPIRIT, 1));
        register("minecraft:netherrack", tags().add(Aspect.EARTH, 1).add(Aspect.ROCK, 1).add(Aspect.FIRE, 1));
        register("minecraft:nether_bricks", tags().add(Aspect.ROCK, 2).add(Aspect.FIRE, 1));
        register("minecraft:glass", tags().add(Aspect.CRYSTAL, 2));
        register("minecraft:snowball", tags().add(Aspect.COLD, 1));
        register("#minecraft:leaves", tags().add(Aspect.PLANT, 2));
        register(List.of("minecraft:short_grass", "minecraft:fern"), tags().add(Aspect.PLANT, 1).add(Aspect.WIND, 1));
        register("minecraft:lily_pad", tags().add(Aspect.PLANT, 2).add(Aspect.WATER, 1));
        register("minecraft:dead_bush", tags().add(Aspect.PLANT, 1).add(Aspect.WIND, 1));
        register("minecraft:vine", tags().add(Aspect.PLANT, 2));
        register("minecraft:wheat_seeds", tags().add(Aspect.PLANT, 1).add(Aspect.EXCHANGE, 1));
        register("minecraft:melon_seeds", tags().add(Aspect.PLANT, 1).add(Aspect.EXCHANGE, 1));
        register("minecraft:pumpkin_seeds", tags().add(Aspect.PLANT, 1).add(Aspect.EXCHANGE, 1));
        register("minecraft:melon_slice", tags().add(Aspect.LIFE, 1));
        register("minecraft:nether_wart", tags().add(Aspect.FUNGUS, 1).add(Aspect.FLUX, 1).add(Aspect.FIRE, 1));
        register("minecraft:ink_sac", tags().add(Aspect.DARK, 1).add(Aspect.FLESH, 1));
        register("minecraft:green_dye", tags().add(Aspect.PLANT, 3));
        register("minecraft:cocoa_beans", tags().add(Aspect.PLANT, 1).add(Aspect.POWER, 2));
        register("minecraft:lapis_lazuli", tags().add(Aspect.VALUABLE, 1).add(Aspect.ROCK, 1));
        register("minecraft:cookie", tags().add(Aspect.LIFE, 1));
        register("minecraft:potion", tags().add(Aspect.WATER, 1).add(Aspect.CRYSTAL, 1));
        register("minecraft:torch", tags().add(Aspect.LIGHT, 1));
        register("#minecraft:logs", tags().add(Aspect.WOOD, 4));
        register("#minecraft:planks", tags().add(Aspect.WOOD, 1));
        register("minecraft:mossy_cobblestone", tags().add(Aspect.ROCK, 2).add(Aspect.PLANT, 1).add(Aspect.FLUX, 1));
        register("minecraft:ice", tags().add(Aspect.COLD, 2).add(Aspect.CRYSTAL, 1).add(Aspect.WATER, 1));
        register("minecraft:poppy", tags().add(Aspect.FLOWER, 4).add(Aspect.FIRE, 1));
        register("minecraft:dandelion", tags().add(Aspect.FLOWER, 4).add(Aspect.LIGHT, 1));
        register("minecraft:cactus", tags().add(Aspect.PLANT, 4).add(Aspect.WATER, 1).add(Aspect.WEAPON, 1));
        register("#minecraft:saplings", tags().add(Aspect.PLANT, 2).add(Aspect.WOOD, 2));
        register("minecraft:brown_mushroom", tags().add(Aspect.FUNGUS, 4));
        register("minecraft:red_mushroom", tags().add(Aspect.FUNGUS, 4));
        register("minecraft:brown_mushroom_block", tags().add(Aspect.FUNGUS, 4));
        register("minecraft:red_mushroom_block", tags().add(Aspect.FUNGUS, 4));
        register("minecraft:sugar_cane", tags().add(Aspect.CROP, 2).add(Aspect.WATER, 2));
        register("minecraft:wheat", tags().add(Aspect.CROP, 2).add(Aspect.LIFE, 2));
        register("minecraft:apple", tags().add(Aspect.CROP, 2).add(Aspect.LIFE, 2));
        register("minecraft:coal_ore", tags().add(Aspect.ROCK, 3).add(Aspect.POWER, 1).add(Aspect.FIRE, 1));
        register("minecraft:coal", tags().add(Aspect.ROCK, 1).add(Aspect.POWER, 2).add(Aspect.FIRE, 2));
        register("minecraft:charcoal", tags().add(Aspect.WOOD, 1).add(Aspect.POWER, 2).add(Aspect.FIRE, 2));
        register("minecraft:redstone_ore", tags().add(Aspect.EARTH, 2).add(Aspect.POWER, 1).add(Aspect.MECHANISM, 1));
        register("minecraft:redstone", tags().add(Aspect.POWER, 2).add(Aspect.MECHANISM, 2));
        register("minecraft:glowstone_dust", tags().add(Aspect.VISION, 1).add(Aspect.LIGHT, 3));
        register("minecraft:glowstone", tags().add(Aspect.VISION, 3).add(Aspect.LIGHT, 10));
        register("minecraft:cobweb", tags().add(Aspect.TRAP, 2).add(Aspect.INSECT, 1).add(Aspect.CLOTH, 1));
        register("minecraft:flint", tags().add(Aspect.ROCK, 1).add(Aspect.TOOL, 1));
        register("minecraft:string", tags().add(Aspect.INSECT, 1).add(Aspect.CLOTH, 1).add(Aspect.TRAP, 1));
        register("minecraft:carrot", tags().add(Aspect.CROP, 2).add(Aspect.VISION, 2));
        register("minecraft:potato", tags().add(Aspect.CROP, 2).add(Aspect.EARTH, 2));
        register("minecraft:baked_potato", tags().add(Aspect.CROP, 2).add(Aspect.LIFE, 2));
        register("minecraft:poisonous_potato", tags().add(Aspect.CROP, 2).add(Aspect.POISON, 2));
        register("minecraft:slime_ball", tags().add(Aspect.CONTROL, 1).add(Aspect.WATER, 1).add(Aspect.FLUX, 1));
        register("minecraft:leather", tags().add(Aspect.FLESH, 1).add(Aspect.CLOTH, 1).add(Aspect.BEAST, 1).add(Aspect.ARMOR, 1));
        register("minecraft:rotten_flesh", tags().add(Aspect.DEATH, 1).add(Aspect.FLESH, 3));
        register("minecraft:feather", tags().add(Aspect.FLIGHT, 2).add(Aspect.WIND, 2));
        register("minecraft:bone", tags().add(Aspect.DEATH, 3).add(Aspect.FLESH, 1));
        register("minecraft:egg", tags().add(Aspect.EXCHANGE, 2).add(Aspect.FLESH, 2));
        register("minecraft:spider_eye", tags().add(Aspect.VISION, 2).add(Aspect.INSECT, 2).add(Aspect.POISON, 2));
        register("minecraft:nether_quartz_ore", tags().add(Aspect.ROCK, 2).add(Aspect.CRYSTAL, 1).add(Aspect.TIME, 1));
        register("minecraft:quartz", tags().add(Aspect.ROCK, 1).add(Aspect.CRYSTAL, 1).add(Aspect.PURE, 1).add(Aspect.VISION, 1));
        register("minecraft:obsidian", tags().add(Aspect.ROCK, 5).add(Aspect.DARK, 1).add(Aspect.FIRE, 2));
        register("minecraft:iron_ore", tags().add(Aspect.METAL, 6).add(Aspect.ROCK, 2));
        register("minecraft:iron_ingot", tags().add(Aspect.METAL, 8));
        register("minecraft:pumpkin", tags().add(Aspect.CROP, 4));
        register("minecraft:gunpowder", tags().add(Aspect.FIRE, 4).add(Aspect.DESTRUCTION, 4));
        register("minecraft:white_wool", tags().add(Aspect.CLOTH, 4).add(Aspect.BEAST, 1));
        register("minecraft:cod", tags().add(Aspect.FLESH, 4).add(Aspect.LIFE, 2).add(Aspect.WATER, 1));
        register("minecraft:cooked_cod", tags().add(Aspect.FIRE, 1).add(Aspect.FLESH, 4).add(Aspect.LIFE, 4));
        register("minecraft:chicken", tags().add(Aspect.FLESH, 4).add(Aspect.LIFE, 2).add(Aspect.BEAST, 1));
        register("minecraft:cooked_chicken", tags().add(Aspect.FIRE, 1).add(Aspect.FLESH, 4).add(Aspect.LIFE, 4));
        register("minecraft:porkchop", tags().add(Aspect.FLESH, 4).add(Aspect.LIFE, 2).add(Aspect.BEAST, 1));
        register("minecraft:cooked_porkchop", tags().add(Aspect.FIRE, 1).add(Aspect.FLESH, 4).add(Aspect.LIFE, 4));
        register("minecraft:beef", tags().add(Aspect.FLESH, 4).add(Aspect.LIFE, 2).add(Aspect.BEAST, 1));
        register("minecraft:cooked_beef", tags().add(Aspect.FIRE, 1).add(Aspect.FLESH, 4).add(Aspect.LIFE, 4));
        register("minecraft:blaze_rod", tags().add(Aspect.FIRE, 6).add(Aspect.MAGIC, 2));
        register("minecraft:lapis_ore", tags().add(Aspect.VALUABLE, 4).add(Aspect.ROCK, 4));
        register("minecraft:gold_ore", tags().add(Aspect.METAL, 6).add(Aspect.ROCK, 2).add(Aspect.VALUABLE, 4));
        register("minecraft:gold_ingot", tags().add(Aspect.METAL, 8).add(Aspect.VALUABLE, 4));
        register("minecraft:saddle", tags().add(Aspect.CONTROL, 4).add(Aspect.CLOTH, 4));
        register("minecraft:ender_pearl", tags().add(Aspect.ELDRITCH, 4).add(Aspect.MAGIC, 4).add(Aspect.CRYSTAL, 4));
        register("minecraft:diamond_ore", tags().add(Aspect.CRYSTAL, 10).add(Aspect.ROCK, 4).add(Aspect.VALUABLE, 2).add(Aspect.PURE, 2));
        register("minecraft:diamond", tags().add(Aspect.CRYSTAL, 12).add(Aspect.VALUABLE, 4).add(Aspect.PURE, 4));
        register("minecraft:ghast_tear", tags().add(Aspect.WATER, 4).add(Aspect.DEATH, 4).add(Aspect.EVIL, 4).add(Aspect.SPIRIT, 4));
        register("#minecraft:skulls", tags().add(Aspect.DEATH, 8).add(Aspect.SPIRIT, 4).add(Aspect.EVIL, 4));
        register("minecraft:emerald_ore", tags().add(Aspect.CRYSTAL, 9).add(Aspect.ROCK, 4).add(Aspect.EXCHANGE, 3).add(Aspect.MAGIC, 3).add(Aspect.VALUABLE, 1));
        register("minecraft:emerald", tags().add(Aspect.CRYSTAL, 10).add(Aspect.EXCHANGE, 4).add(Aspect.MAGIC, 4).add(Aspect.VALUABLE, 2));
        register("minecraft:music_disc_11", tags().add(Aspect.SOUND, 12).add(Aspect.FIRE, 4).add(Aspect.VALUABLE, 4));
        register("minecraft:music_disc_13", tags().add(Aspect.SOUND, 12).add(Aspect.WATER, 4).add(Aspect.VALUABLE, 4));
        register("minecraft:music_disc_cat", tags().add(Aspect.SOUND, 12).add(Aspect.BEAST, 4).add(Aspect.VALUABLE, 4));
        register("minecraft:music_disc_chirp", tags().add(Aspect.SOUND, 12).add(Aspect.EARTH, 4).add(Aspect.VALUABLE, 4));
        register("minecraft:music_disc_far", tags().add(Aspect.SOUND, 12).add(Aspect.ELDRITCH, 4).add(Aspect.VALUABLE, 4));
        register("minecraft:music_disc_mall", tags().add(Aspect.SOUND, 12).add(Aspect.EXCHANGE, 4).add(Aspect.VALUABLE, 4));
        register("minecraft:music_disc_mellohi", tags().add(Aspect.SOUND, 12).add(Aspect.MOTION, 4).add(Aspect.VALUABLE, 4));
        register("minecraft:music_disc_stal", tags().add(Aspect.SOUND, 12).add(Aspect.EVIL, 4).add(Aspect.VALUABLE, 4));
        register("minecraft:music_disc_strad", tags().add(Aspect.SOUND, 12).add(Aspect.CONTROL, 4).add(Aspect.VALUABLE, 4));
        register("minecraft:music_disc_ward", tags().add(Aspect.SOUND, 12).add(Aspect.MAGIC, 4).add(Aspect.VALUABLE, 4));
        register("minecraft:music_disc_blocks", tags().add(Aspect.SOUND, 12).add(Aspect.CRAFT, 4).add(Aspect.VALUABLE, 4));
        register("minecraft:music_disc_wait", tags().add(Aspect.SOUND, 12).add(Aspect.TRAP, 4).add(Aspect.VALUABLE, 4));
        register("minecraft:nether_star", tags().add(Aspect.ELDRITCH, 16).add(Aspect.MAGIC, 16).add(Aspect.PURE, 16).add(Aspect.DARK, 16));
        register("minecraft:chainmail_helmet", tags().add(Aspect.METAL, 30));
        register("minecraft:chainmail_chestplate", tags().add(Aspect.METAL, 50));
        register("minecraft:chainmail_leggings", tags().add(Aspect.METAL, 45));
        register("minecraft:chainmail_boots", tags().add(Aspect.METAL, 25));
        register("minecraft:paper", tags().add(Aspect.KNOWLEDGE, 2).add(Aspect.CROP, 2).add(Aspect.WATER, 2));
        register("minecraft:book", tags().add(Aspect.KNOWLEDGE, 5).add(Aspect.CROP, 5).add(Aspect.WATER, 5).add(Aspect.BEAST, 2).add(Aspect.FLESH, 2));
        complex("minecraft:stone_bricks", tags());
        register("minecraft:mossy_stone_bricks", copy("minecraft:stone_bricks").remove(Aspect.ROCK, 1).add(Aspect.PLANT, 1));
        register("minecraft:cracked_stone_bricks", copy("minecraft:stone_bricks").remove(Aspect.ROCK, 1).add(Aspect.DESTRUCTION, 1));
        register("minecraft:chiseled_stone_bricks", copy("minecraft:stone_bricks").remove(Aspect.ROCK, 1).add(Aspect.VALUABLE, 1));
        complex("minecraft:sandstone", tags().add(Aspect.ROCK, 2).remove(Aspect.EARTH, 2));
        register("minecraft:chiseled_sandstone", copy("minecraft:sandstone").remove(Aspect.EARTH, 1).add(Aspect.MAGIC, 1));
        register("minecraft:cut_sandstone", copy("minecraft:sandstone").remove(Aspect.EARTH, 1).add(Aspect.VALUABLE, 1));
        complex("minecraft:melon", tags().add(Aspect.CROP, 2).remove(Aspect.LIFE, 4));
        complex("minecraft:ender_eye", tags().add(Aspect.VISION, 4));
        complex("minecraft:arrow", tags().add(Aspect.WEAPON, 1));
        complex("minecraft:glass_bottle", tags().add(Aspect.VOID, 1));
        complex("minecraft:chest", tags().add(Aspect.VOID, 4));
        complex("minecraft:golden_apple", tags().add(Aspect.MAGIC, 2).add(Aspect.HEAL, 4));
        complex("minecraft:enchanted_golden_apple", tags().add(Aspect.MAGIC, 4).add(Aspect.HEAL, 8));
        complex("minecraft:bowl", tags().add(Aspect.VOID, 1));
        complex("minecraft:mushroom_stew", tags().add(Aspect.LIFE, 4));
        complex("minecraft:minecart", tags().add(Aspect.MECHANISM, 2).add(Aspect.MOTION, 4));
        complex("minecraft:iron_door", tags().add(Aspect.MECHANISM, 2).add(Aspect.MOTION, 1));
        complex("minecraft:oak_door", tags().add(Aspect.MECHANISM, 1).add(Aspect.MOTION, 1));
        complex("minecraft:oak_boat", tags().add(Aspect.WATER, 4).add(Aspect.MOTION, 4));
        complex("minecraft:flint_and_steel", tags().add(Aspect.FIRE, 4));
        complex("minecraft:fishing_rod", tags().add(Aspect.WATER, 1).add(Aspect.TOOL, 1));
        register("minecraft:bucket", tags().add(Aspect.METAL, 13).add(Aspect.VOID, 1));
        complex("minecraft:water_bucket", copy("minecraft:bucket").add(Aspect.WATER, 4));
        complex("minecraft:lava_bucket", copy("minecraft:bucket").add(Aspect.FIRE, 6).add(Aspect.ROCK, 2).add(Aspect.WATER, 1));
        complex("minecraft:milk_bucket", copy("minecraft:bucket").add(Aspect.LIFE, 2).add(Aspect.HEAL, 2).add(Aspect.WATER, 2));
        complex("minecraft:brewing_stand", tags().add(Aspect.MAGIC, 2).add(Aspect.WATER, 2));
        complex("minecraft:stone_button", tags().add(Aspect.MECHANISM, 1));
        complex("minecraft:detector_rail", tags().add(Aspect.MECHANISM, 2).add(Aspect.VISION, 2));
        complex("minecraft:powered_rail", tags().add(Aspect.MECHANISM, 2));
        complex("minecraft:oak_fence_gate", tags().add(Aspect.MECHANISM, 1).add(Aspect.MOTION, 1));
        complex("minecraft:oak_pressure_plate", tags().add(Aspect.MECHANISM, 1));
        complex("minecraft:stone_pressure_plate", tags().add(Aspect.MECHANISM, 1));
        complex("minecraft:lever", tags().add(Aspect.CONTROL, 1));
        complex("minecraft:redstone_torch", tags().add(Aspect.MECHANISM, 2));
        complex("minecraft:piston", tags().add(Aspect.MECHANISM, 2).add(Aspect.MOTION, 4));
        register("minecraft:sticky_piston", copy("minecraft:piston").add(Aspect.EXCHANGE, 3).add(Aspect.WATER, 1).add(Aspect.FLESH, 1));
        complex("minecraft:jukebox", tags().add(Aspect.SOUND, 8).add(Aspect.MECHANISM, 2));
        complex("minecraft:note_block", tags().add(Aspect.SOUND, 4).add(Aspect.MECHANISM, 1));
        complex("minecraft:oak_trapdoor", tags().add(Aspect.MOTION, 1));
        complex("minecraft:furnace", tags().add(Aspect.FIRE, 2));
        complex("minecraft:enchanting_table", tags().add(Aspect.MAGIC, 8));
        register("minecraft:crafting_table", tags().add(Aspect.CRAFT, 4).add(Aspect.WOOD, 3));
        complex("minecraft:clock", tags().add(Aspect.TIME, 4));
        complex("minecraft:repeater", tags().add(Aspect.TIME, 1));
        register("minecraft:written_book", copy("minecraft:book").add(Aspect.TIME, 1).remove(Aspect.BEAST, 2));
        complex("minecraft:beacon", tags().add(Aspect.CONTROL, 2).add(Aspect.MAGIC, 2));
        complex("minecraft:anvil", tags().add(Aspect.CRAFT, 2).add(Aspect.TOOL, 2));
        register("minecraft:chipped_anvil", copy("minecraft:anvil").remove(Aspect.CRAFT, 1).remove(Aspect.METAL, 20));
        register("minecraft:damaged_anvil", copy("minecraft:anvil").remove(Aspect.CRAFT, 1).remove(Aspect.TOOL, 1).remove(Aspect.METAL, 40));
        complex("minecraft:oak_button", tags().add(Aspect.MECHANISM, 1));
        complex("minecraft:carrot_on_a_stick", tags().add(Aspect.CONTROL, 4));
        complex("minecraft:flower_pot", tags().add(Aspect.VOID, 1).add(Aspect.LIFE, 1));
        complex("minecraft:golden_carrot", tags().add(Aspect.MAGIC, 2));
        register("thaumcraft:essentia_phial", tags().add(Aspect.VOID, 1).add(Aspect.CRYSTAL, 1));
        register("thaumcraft:native_gold_cluster", tags().add(Aspect.METAL, 12).add(Aspect.ROCK, 2).add(Aspect.VALUABLE, 8));
        register("thaumcraft:native_iron_cluster", tags().add(Aspect.METAL, 12).add(Aspect.ROCK, 2));
        register("thaumcraft:obsidian_totem", tags().add(Aspect.ROCK, 4).add(Aspect.DARK, 2).add(Aspect.FIRE, 2).add(Aspect.ELDRITCH, 2));
        register("thaumcraft:greatwood_log", tags().add(Aspect.WOOD, 5).add(Aspect.MAGIC, 1));
        register("thaumcraft:silverwood_log", tags().add(Aspect.WOOD, 4).add(Aspect.MAGIC, 2).add(Aspect.PURE, 2));
        register("thaumcraft:greatwood_leaves", tags().add(Aspect.PLANT, 2));
        register("thaumcraft:silverwood_leaves", tags().add(Aspect.PLANT, 1).add(Aspect.PURE, 1));
        register("thaumcraft:greatwood_sapling", tags().add(Aspect.PLANT, 2).add(Aspect.WOOD, 2).add(Aspect.MAGIC, 1));
        register("thaumcraft:silverwood_sapling", tags().add(Aspect.PLANT, 2).add(Aspect.WOOD, 2).add(Aspect.MAGIC, 4));
        register("thaumcraft:shimmerleaf", tags().add(Aspect.FLOWER, 2).add(Aspect.EXCHANGE, 2).add(Aspect.MAGIC, 2));
        register("thaumcraft:cinderpearl", tags().add(Aspect.FLOWER, 2).add(Aspect.FIRE, 2).add(Aspect.MAGIC, 2));
        register("thaumcraft:cinnabar_ore", tags().add(Aspect.ROCK, 2).add(Aspect.METAL, 3).add(Aspect.VISION, 3));
        register("thaumcraft:amber_ore", tags().add(Aspect.ROCK, 2).add(Aspect.TRAP, 3).add(Aspect.WOOD, 1).add(Aspect.CRYSTAL, 2));
        register("thaumcraft:quicksilver", tags().add(Aspect.MOTION, 1).add(Aspect.METAL, 4).add(Aspect.POISON, 1).add(Aspect.VISION, 4));
        register("thaumcraft:zombie_brain", tags().add(Aspect.FLESH, 2).add(Aspect.KNOWLEDGE, 4).add(Aspect.EVIL, 2).add(Aspect.DEATH, 2));
        register("thaumcraft:amber", tags().add(Aspect.TRAP, 4).add(Aspect.WOOD, 2).add(Aspect.CRYSTAL, 2));
        register("thaumcraft:knowledge_fragment", tags().add(Aspect.KNOWLEDGE, 16));
        register("thaumcraft:beef_nugget", tags().add(Aspect.FLESH, 1));
        register("thaumcraft:chicken_nugget", tags().add(Aspect.FLESH, 1));
        register("thaumcraft:pork_nugget", tags().add(Aspect.FLESH, 1));
        complex("thaumcraft:triple_meat_treat", tags().add(Aspect.HEAL, 1).remove(Aspect.CROP, 1));
        register("thaumcraft:air_shard", tags().add(Aspect.MAGIC, 2).add(Aspect.WIND, 2).add(Aspect.MOTION, 2).add(Aspect.CRYSTAL, 2));
        register("thaumcraft:fire_shard", tags().add(Aspect.MAGIC, 2).add(Aspect.FIRE, 2).add(Aspect.POWER, 2).add(Aspect.CRYSTAL, 2));
        register("thaumcraft:water_shard", tags().add(Aspect.MAGIC, 2).add(Aspect.WATER, 2).add(Aspect.COLD, 2).add(Aspect.CRYSTAL, 2));
        register("thaumcraft:earth_shard", tags().add(Aspect.MAGIC, 2).add(Aspect.EARTH, 2).add(Aspect.ROCK, 2).add(Aspect.CRYSTAL, 2));
        register("thaumcraft:vis_shard", tags().add(Aspect.MAGIC, 6).add(Aspect.CRYSTAL, 2));
        register("thaumcraft:dull_shard", tags().add(Aspect.MAGIC, 2).add(Aspect.CRYSTAL, 2));
        complex("thaumcraft:thaumometer", tags().add(Aspect.MAGIC, 4).add(Aspect.KNOWLEDGE, 4).add(Aspect.VISION, 4));
        complex("thaumcraft:goggles_of_revealing", tags().add(Aspect.VISION, 4));
        complex("thaumcraft:table", tags().add(Aspect.TOOL, 1));
        register("thaumcraft:arcane_worktable", copy("thaumcraft:table").add(Aspect.CRAFT, 4).add(Aspect.MAGIC, 2));
        register("thaumcraft:wand_apprentice", tags().add(Aspect.MAGIC, 4).add(Aspect.TOOL, 2).add(Aspect.CRAFT, 2));
        register("thaumcraft:crucible", copy("minecraft:cauldron").add(Aspect.CRAFT, 4).add(Aspect.MAGIC, 4));
        register("thaumcraft:white_tallow_candle", tags().add(Aspect.LIGHT, 4).add(Aspect.FLESH, 3).add(Aspect.CLOTH, 1).add(Aspect.MAGIC, 1));
        register("thaumcraft:thaumonomicon", copy("minecraft:bookshelf").add(Aspect.MAGIC, 4).merge(Aspect.KNOWLEDGE, 8));
        registerEssences();
    }
}
