modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
bannerFile="thaumcraft_logo.png"
iconFile="thaumcraft_icon.png"
logoFile="thaumcraft_icon.png"
authors="${mod_authors}"
description='''
Adding a touch of magic to Minecraft. Unofficial port of Thaumcraft 3.0.5e.
'''

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mixins]]
config="thaumcraft.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jei"
    type="optional"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"
